spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expert
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace

jwt:
  secret:
    key: dGhpc2lzQmFzZTY0RW5jb2RlZEtleU9mMzJCeXRlcyE=
